language: ruby
cache:
  - bundler
  - apt
before_install:
  - curl http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
  - echo "deb http://packages.couchbase.com/ubuntu precise precise/main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y libcouchbase-dev
services:
  - memcached
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2
  - rbx-2.1.1
  - ree
