language: ruby
cache:
  - bundler
  - apt
before_install:
  - curl http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
  - echo "deb http://packages.couchbase.com/ubuntu precise precise/main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y libcouchbase-dev
services:
  - memcached
rvm:
  - 1.9
  - 2.0
  - 2.1
